### ISSUE TITLE
RangeError on empty list provided to steps

### ISSUE THREAD

**Issue by jlnrrg** [talamaska/onboarding_overlay#25]
Giving that I track which steps were shown using `SharedPreferences`.
And reduce this list I provide to `Onboarding(steps: ` for each already shown `OnboardingStep`:
This very fast results to an empty list being provided as steps.

Now in turn when the following code is called, this leads to the following error message.

Code:

```dart
    WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
      final onboarding = Onboarding.of(context);
      onboarding?.show();
    });
```

Error:
```bash
RangeError (index): Invalid value: Valid value range is empty: 0
```

**Comment by talamaska** [comment]
uhm empty steps doesn't sound right. Why don't you try calling the other show methods
instead of calling show, try showWithSteps.
Other than that what do you expect to happen? just not start and not throwing error?
Do you update the steps passed to the Onboarding dynamically on change?

**Comment by jlnrrg** [comment]
Because the other method (`showWithSteps`) throws the same error :smile:.
I personally would expect it to just not start.

I do exactly that:

`onChanged: (i) => 
            context.read<SharedPreferencesService>().setOnboardingDone(i),`

**Comment by talamaska** [comment]
ok, it seems I haven't added any safe check for empty steps. I didn't expect someone to change that dynamically. 
Here is what I do. Similarly to you I store which steps were completed, then I check if there are completed steps, it's a number actually. Then If I have completed all steps I just don't start the onboarding. Else I generate a list with indexes using that number and the total number of steps and start the onboarding with showWithSteps. Obviously those safe-checks are outside of the onboarding in my app.

for example I have 8 steps , you completed step 5 (index 4). The user closed it, or you closed it. 
next time the user navigates to a page or opens the app or some other activity, I see the user have completed step 5. this means I need to call the showWithSteps(5, [5,6,7]) instead of just show();

I'll add some safety measure to not be able to start the onaboarding with 0 steps, bet that honestly is your responsibility :)
Will be back to you when I publish pre.11.

**Comment by jlnrrg** [comment]
I might use your package other than intended, which might be the reason for our different approach.
So I'd like to argue why allowing empty steps would be good.

I use create a different Onboarding for each section of my app (this results in about +10 onboarding widget with different steps all together. To manage that I use a seperate logic which tracks the indexes that were already viewed. 

The Onboardings encapsulate my own `OnboardingFocus` so whenever the user first encounters the page, the onboardings are started. Now that I know that I should check if onboarding has steps provided before calling any method, that can be easy implemented by me, but future users might not be so lucky to encounter this early on, so the possibility to provide an empty list to Onboarding might still be a great idea anyway.

<details><summary>OnboardingFocus</summary>
```dart
class OnboardingFocus extends StatefulWidget {
  OnboardingFocus({Key? key, required this.child}) : super(key: key);

  final Widget child;

  @override
  _OnboardingFocusState createState() => _OnboardingFocusState();
}

class _OnboardingFocusState extends State<OnboardingFocus> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
      final onboarding = Onboarding.of(context);
      onboarding?.showWithSteps(0, []);
    });
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```
</details>

**Comment by talamaska** [comment]
Right. Yes, no worries. 
I do use it differently. I use only one giant onboarding with 15 steps, and show portions of 5 steps on different pages. 
Just different approach like you said. Working on fix.

**Comment by talamaska** [comment]
https://pub.dev/packages/onboarding_overlay/versions/3.0.0-pre.11

**Comment by jlnrrg** [comment]
Works like a charm thanks as always.
(Just to make you aware, that you have a [competitor](https://pub.dev/packages/pal_widgets) since recently)

**Comment by talamaska** [comment]
Actually, pal is not just widgets. I think it is a SaaS. You can control the onboarding steps remotely. It's a different thing. I'm well aware about it's existence, but thanks for sharing https://pub.dev/packages/pal

**Comment by jlnrrg** [comment]
right. You are welcome.
another addition: I noted, that you print the debug messages ('overlay hit true') ('label hit') by default. You might want to change this, as it overloads the debug console quite fast.
