### ISSUE TITLE
No hole in web

### ISSUE THREAD

**Issue by amit20897** [talamaska/onboarding_overlay#37]
Works perfectly on android and iOS, doesn't seem to show the hole in the web, images as examples:
<img width="674" alt="Screen Shot 2022-10-08 at 0 18 19" src="https://user-images.githubusercontent.com/21218993/194654497-40f1f57b-f0ac-4677-b10a-fea61d6fd22a.png">
<img width="675" alt="Screen Shot 2022-10-08 at 0 18 00" src="https://user-images.githubusercontent.com/21218993/194654508-613aeb6a-f52d-479d-8fc4-bf210a092a5b.png">

**Comment by talamaska** [comment]
I don't know what's the reason. Welcoming PR that fix this issue.

**Comment by vdaele** [comment]
I'm running into the same issue

**Comment by talamaska** [comment]
Seems like an issue in flutter [#44572](https://github.com/flutter/flutter/issues/44572)

**Comment by vdaele** [comment]
Thnaks for looking into this! Much appreciated!

I can indeed confirm that, when using the html renderer, that I run into the CombinePaths error and when using canvaskit, I see no holes.

Would using a ColorFiltered widget be a (temporay) workaround 
(https://stackoverflow.com/questions/60357361/create-widget-with-transparent-hole-inside) ?

**Comment by talamaska** [comment]
I don't think so, cause there are hitTests happening and ability to click on the item under the hole.

**Comment by andyskw** [comment]
Hey,

I tried to fix the mentioned issue, as I would love to use your package in a web project, but sadly the issue prevents me to do so. So after some experimentation, this is how far I got. I am not familiar with your whole codebase though, so there may be still cases, where it does not work well, but on web at least, the problem seems to be gone.
If you could test it on mobile, then I think we are done here. :)

![Screenshot 2024-03-26 104906](https://github.com/talamaska/onboarding_overlay/assets/662457/38eaecda-ecf3-443b-80c1-32cbb7473327)

I also ran your example app (copy-pasted from the pub.dev package's example tab), this is how it looks right now:
* https://www.youtube.com/watch?v=RiVXbpEjED8
